export const FETCH_CARD_REQUEST = 'FETCH_CARD_REQUEST';
export const FETCH_CARD_SUCCESS = 'FETCH_CARD_SUCCESS';
export const FETCH_CARD_FAILED = 'FETCH_CARD_FAILED';

export const SORT_CARD_ASC = 'SORT_CARD_ASC';
export const SORT_CARD_DESC = 'SORT_CARD_DESC';

export const SEARCH_CARDS = 'SEARCH_CARDS';

export const FETCH_CARD_FILTER_REQUEST = 'FETCH_CARD_FILTER_REQUEST';
export const FETCH_CARD_FILTER_SUCCESS = 'FETCH_CARD_FILTER_SUCCESS';
export const FETCH_CARD_FILTER_FAILED = 'FETCH_CARD_FILTER_FAILED';


export const FETCH_CARD_DETAIL_REQUEST = 'FETCH_CARD_DETAIL_REQUEST';
export const FETCH_CARD_DETAIL_SUCCESS = 'FETCH_CARD_DETAIL_SUCCESS';
export const FETCH_CARD_DETAIL_FAILED = 'FETCH_CARD_DETAIL_FAILED';

